language: java
jdk:
  - oraclejdk8
script: "gradle build"
branches:
  only:
    - develop
    - feature/study-cha
env:
  - TERM=dumb
after_success:
  - gradle cobertura coveralls
notifications:
  slack: codechobostudy:7xxE3u0mOPli3DRz6cKiIz51
  email:
    - changhwaoh.co@gmail.com