spring.template.cache: false
webjars.requirejs.newModules:

app:
  version: de4db33f

spring.social:
  # SPRING SOCIAL FACEBOOK (FacebookAutoConfiguration)
  facebook:
    app-id: # your application's Facebook App ID
    app-secret: # your application's Facebook App Secret
  # SPRING SOCIAL TWITTER (TwitterAutoConfiguration)
  twitter:
    app-id: # your application's Twitter App ID
    app-secret: # your application's Twitter App Secret

spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  jpa:
    show-sql: true
    hibernate:
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      format-sql: true

